# Generated by Django 4.1.2 on 2022-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_project', '0002_alter_book_reader_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='book',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
